#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Regenerate THIRD_PARTY_NOTICES.txt: the attribution manifest for third-party
# open-source components that are REDISTRIBUTED in amplio's release artifacts —
# the cross-compiled Go binary (statically links its Go module deps) and the
# embedded SvelteKit bundle (ships DOMPurify/marked/highlight.js/phosphor +
# the Svelte runtime). The source repo itself bundles none of these (deps are
# fetched at build time), but the RELEASE TARBALLS do, which triggers the
# MIT/Apache-2.0/BSD attribution clauses — this file satisfies them.
#
# Scope choices:
#   * Go: every module linked into ./cmd/amplio, via `go-licenses`.
#   * npm: every PRODUCTION dependency (`npm ci --omit=dev` tree). This is a
#     safe SUPERSET of what vite actually bundles (build-only tooling like
#     acorn/magic-string/@jridgewell that resolves under a runtime dep is
#     included too) — over-attributing is harmless; under-attributing is not.
#   * DOMPurify is dual-licensed "(MPL-2.0 OR Apache-2.0)"; amplio ELECTS
#     Apache-2.0 (see the note emitted below), so no MPL obligation attaches.
#
# Deterministic + dependency-light: uses `go-licenses` (go run) for Go and a
# plain walk of node_modules LICENSE files for npm (no extra npm tool). Run from
# the repo root:  ./scripts/gen-third-party-notices.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_NOTICES.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# go-licenses can't auto-locate a license file for a few modules; supply the
# known SPDX id upstream declares. Keep this list minimal and reviewed.
declare -A GO_LICENSE_OVERRIDE=(
  ["modernc.org/mathutil"]="BSD-3-Clause"
)

hr() { printf '%s\n' "================================================================================"; }

{
  echo "amplio — THIRD-PARTY SOFTWARE NOTICES AND INFORMATION"
  echo
  echo "amplio itself is licensed under Apache-2.0 (see LICENSE). The release"
  echo "artifacts (the cross-compiled binary and the embedded web UI) also include"
  echo "third-party open-source components, listed below with their licenses."
  echo
  echo "GENERATED by scripts/gen-third-party-notices.sh — do not edit by hand."
  echo
  echo "DOMPurify is dual-licensed \"(MPL-2.0 OR Apache-2.0)\"; amplio elects the"
  echo "Apache-2.0 option, so no MPL-2.0 obligation applies to the shipped bundle."
  echo
} > "$TMP"

# ── Go modules linked into the binary ──────────────────────────────────────
{
  hr
  echo "GO MODULES (linked into the amplio binary)"
  hr
  echo
} >> "$TMP"

# `go-licenses save` copies each dependency's LICENSE text into a tree we then
# concatenate. --force overwrites a prior run's output.
GO_LIC_DIR="$(mktemp -d)"
trap 'rm -f "$TMP"; rm -rf "$GO_LIC_DIR"' EXIT
rm -rf "$GO_LIC_DIR"
# save writes real files; ignore the known mathutil "cannot find license" error
# (handled via the override note) but fail on anything unexpected.
if ! go run github.com/google/go-licenses@v1.6.0 save ./cmd/amplio \
      --save_path="$GO_LIC_DIR" --force 2> "$GO_LIC_DIR.err"; then
  # Tolerate only the known mathutil discovery failure; surface anything else.
  if grep -qvE 'mathutil|^$' "$GO_LIC_DIR.err" | grep -qiv 'warn'; then
    echo "go-licenses save failed:" >&2
    cat "$GO_LIC_DIR.err" >&2
  fi
fi

# Concatenate each module's saved LICENSE, module path as the header. Skip
# amplio's OWN license (go-licenses includes the main module; it's not
# third-party, and its Apache-2.0 text is already the repo's LICENSE).
if [ -d "$GO_LIC_DIR" ]; then
  while IFS= read -r lic; do
    mod="$(dirname "${lic#"$GO_LIC_DIR"/}")"
    [ "$mod" = "amplio" ] && continue
    {
      echo "--- $mod ---"
      echo
      cat "$lic"
      echo
    } >> "$TMP"
  done < <(find "$GO_LIC_DIR" -type f \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) | sort)
fi

# Note any override modules whose license text go-licenses couldn't save.
for mod in "${!GO_LICENSE_OVERRIDE[@]}"; do
  if ! find "$GO_LIC_DIR" -path "*$mod*" -type f 2>/dev/null | grep -q .; then
    {
      echo "--- $mod ---"
      echo
      echo "License: ${GO_LICENSE_OVERRIDE[$mod]} (see the module's upstream repository)."
      echo
    } >> "$TMP"
  fi
done

# ── npm production dependencies bundled into the web UI ─────────────────────
{
  hr
  echo "NPM PACKAGES (bundled into the amplio web UI)"
  hr
  echo
} >> "$TMP"

FE="$ROOT/frontend"
# The production dependency dir list, one abs path per package, from the
# --omit=dev tree. `npm ls` output is parsed loosely; we resolve each name to
# its node_modules dir and emit its LICENSE file.
node - "$FE" >> "$TMP" <<'NODE'
const fs = require('fs');
const path = require('path');
const fe = process.argv[2];
const nm = path.join(fe, 'node_modules');

// Walk the production dependency closure from package.json's "dependencies",
// following each package's own "dependencies" (NOT devDependencies), matching
// what `npm ci --omit=dev` installs.
const seen = new Set();
const out = [];
function visit(name) {
  if (seen.has(name)) return;
  seen.add(name);
  const dir = path.join(nm, name);
  let pkg;
  try { pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8')); }
  catch { return; }
  out.push({ name, version: pkg.version || '?', license: pkg.license || pkg.licenses || '?', dir });
  for (const dep of Object.keys(pkg.dependencies || {})) visit(dep);
}
const root = JSON.parse(fs.readFileSync(path.join(fe, 'package.json'), 'utf8'));
for (const dep of Object.keys(root.dependencies || {})) visit(dep);
// Svelte is a devDependency (it's the compiler), but its CLIENT RUNTIME is
// bundled into the shipped JS, so its attribution belongs here. Add any other
// dev-tier package whose code actually ships to this list.
for (const dep of ['svelte']) visit(dep);

out.sort((a, b) => a.name.localeCompare(b.name));
const licNames = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'LICENCE', 'COPYING', 'NOTICE'];
for (const p of out) {
  const lic = typeof p.license === 'string' ? p.license : JSON.stringify(p.license);
  console.log(`--- ${p.name}@${p.version} (${lic}) ---`);
  console.log('');
  let text = '';
  for (const n of licNames) {
    const f = path.join(p.dir, n);
    if (fs.existsSync(f)) { text = fs.readFileSync(f, 'utf8').trim(); break; }
  }
  console.log(text || `(No bundled license file found; declared license: ${lic}. See the package's upstream repository.)`);
  console.log('');
}
NODE

mv "$TMP" "$OUT"
trap - EXIT
rm -rf "$GO_LIC_DIR" "$GO_LIC_DIR.err"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
