# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""The two shell scripts that run on a TPU VM: boot-time setup and one job.

Both are generated here rather than shipped as files so that the launcher can
hand the VM everything it needs in a single metadata value / single upload.
"""

from __future__ import annotations

import dataclasses
import os
import shlex

_HERE = os.path.dirname(os.path.abspath(__file__))

DEFAULT_VENV = '/opt/simply_venv'
DEFAULT_CODE_DIR = '/opt/simply'
DEFAULT_ASSET_DIR = '/opt/simply_assets'


def _agent_source() -> str:
  with open(os.path.join(_HERE, 'agent.py')) as f:
    return f.read()


def startup_script() -> str:
  """VM `startup-script` metadata: install and run the GCS control agent.

  Re-runs on every boot and is idempotent. Deliberately does *not* build the
  python environment: that is the job script's business, so its progress shows
  up in the job log instead of in an invisible boot log.
  """
  return f'''#!/bin/bash
# Generated by tasks/research_bench/launch/remote.py
set -x
mkdir -p /opt/simply-agent /var/lib/simply-agent
cat > /opt/simply-agent/agent.py <<'SIMPLY_AGENT_EOF'
{_agent_source()}
SIMPLY_AGENT_EOF
cat > /etc/systemd/system/simply-agent.service <<'UNIT_EOF'
[Unit]
Description=Simply GCS control-plane agent
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/python3 /opt/simply-agent/agent.py
Restart=always
RestartSec=5
User=root
StandardOutput=append:/var/log/simply-agent.log
StandardError=append:/var/log/simply-agent.log

[Install]
WantedBy=multi-user.target
UNIT_EOF
cat > /etc/systemd/system/simply-agent-watchdog.service <<'WD_EOF'
[Unit]
Description=Restart the Simply agent if it stops touching its liveness file

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'f=/var/lib/simply-agent/alive; [ -f $f ] && [ $(( $(date +%%s) - $(stat -c %%Y $f) )) -lt 180 ] || systemctl restart simply-agent.service'
WD_EOF
cat > /etc/systemd/system/simply-agent-watchdog.timer <<'WDT_EOF'
[Unit]
Description=Check the Simply agent every minute

[Timer]
OnBootSec=2min
OnUnitActiveSec=1min

[Install]
WantedBy=timers.target
WDT_EOF
systemctl daemon-reload
systemctl enable --now simply-agent.service
systemctl restart simply-agent.service
systemctl enable --now simply-agent-watchdog.timer
'''


@dataclasses.dataclass(frozen=True)
class JobSpec:
  """Everything one seed needs on the VM."""

  job_id: str
  seed: int
  run_dir: str  # gs://<bucket>/<experiment>/seed_<seed>
  status_url: str  # gs://<bucket>/<experiment>/_ctl/<job_id>.status
  code_url: str  # gs://<bucket>/<experiment>/_code/code-<sha>.tar.gz
  command: tuple[str, ...]
  assets_url: str = ''  # gs://<bucket>/assets  (models/ datasets/ vocabs/)
  assets_mode: str = 'mirror'  # 'mirror' to local disk, or 'direct' gs:// env
  assets_include: tuple[str, ...] = ()  # subpaths to mirror, e.g. vocabs
  verify_assets: bool = False  # crc32c every mirrored file before running
  env: tuple[tuple[str, str], ...] = ()
  apt_packages: tuple[str, ...] = ()
  venv: str = DEFAULT_VENV
  code_dir: str = DEFAULT_CODE_DIR
  asset_dir: str = DEFAULT_ASSET_DIR
  pip_extras: str = 'tpu,gcloud'


def _assets_block(spec: JobSpec) -> str:
  if not spec.assets_url:
    return 'echo "no asset cache configured"'
  base = spec.assets_url.rstrip('/')
  if spec.assets_mode == 'direct':
    return '\n'.join([
        f'export SIMPLY_MODELS={shlex.quote(base + "/models")}',
        f'export SIMPLY_DATASETS={shlex.quote(base + "/datasets")}',
        f'export SIMPLY_VOCABS={shlex.quote(base + "/vocabs")}',
    ])
  # The full cache is ~90 GB; a task that needs C4 and one vocab should not
  # pay for every checkpoint in it.
  parts = ' '.join(shlex.quote(p) for p in
                   (spec.assets_include or ('models', 'datasets', 'vocabs')))
  return f'''mkdir -p {spec.asset_dir}
# Sliced downloads stitch a file from parallel ranges and a *resumed* slice is
# not checksum-validated end to end -- a 45 GB checkpoint then lands with the
# right size and a corrupt chunk, which rsync (size+mtime) will never notice
# and which only surfaces as a tensorstore "Truncated Zstd stream" much later.
export CLOUDSDK_STORAGE_SLICED_OBJECT_DOWNLOAD_THRESHOLD=0
for part in {parts}; do
  gcloud storage ls "{base}/$part" >/dev/null 2>&1 || continue
  mkdir -p "{spec.asset_dir}/$part"
  # --delete-unmatched...: a restaged asset must not leave a ghost directory
  # behind on the VM (a stale checkpoint layout silently loads the wrong tree).
  gcloud storage rsync -r --delete-unmatched-destination-objects \\
    "{base}/$part" "{spec.asset_dir}/$part" || exit 1
done
export SIMPLY_MODELS={spec.asset_dir}/models
export SIMPLY_DATASETS={spec.asset_dir}/datasets
export SIMPLY_VOCABS={spec.asset_dir}/vocabs
{_verify_assets_cmd(spec)}'''


def _protos_block(spec: JobSpec) -> str:
  """The serving gRPC stubs are generated, not checked in (setup/gen_protos.py).

  `simply.eval.page_decode_eval` imports them at module load, so every eval
  task needs them built on the VM right after the install.
  """
  if 'serving' not in spec.pip_extras.split(','):
    return '      :  # serving stubs not needed'
  return ('      (cd "$CODE_DIR" && "$VENV/bin/python" setup/gen_protos.py) '
          '|| exit 1')


def _verify_assets_cmd(spec: JobSpec) -> str:
  """crc32c the mirrored cache against the staged manifest before running.

  Structural checks cannot see a file that has the right size and the wrong
  bytes, which is exactly what a resumed sliced download produces.
  """
  if not spec.verify_assets:
    return ': # asset bytes not verified (--verify-assets)'
  return ('python -m tasks.research_bench.setup.prepare_assets '
          'verify --hash || exit 1')


def _apt_block(spec: JobSpec) -> str:
  """Extra system packages (e.g. bubblewrap for the code-execution evals)."""
  if not spec.apt_packages:
    return '    :  # no extra system packages'
  pkgs = ' '.join(shlex.quote(p) for p in spec.apt_packages)
  return f'    apt_get install {pkgs} || exit 1'


def job_script(spec: JobSpec) -> str:
  """One seed, start to finish: env, code, assets, run, log, exit status."""
  def indent(text: str) -> str:
    return '\n'.join('  ' + l for l in text.splitlines())

  env_lines = indent('\n'.join(
      f'export {k}={shlex.quote(v)}' for k, v in spec.env) or '# (no extra env)')
  command = ' '.join(shlex.quote(c) for c in spec.command)
  return f'''#!/bin/bash
# Generated by tasks/research_bench/launch/remote.py -- one seed.
set -uo pipefail
export HOME=${{HOME:-/root}}
export DEBIAN_FRONTEND=noninteractive
# grain's prefetch workers open a shared-memory segment per in-flight element;
# the image's 1024-fd default makes a real training config die with EMFILE.
ulimit -n 1048576 2>/dev/null || ulimit -n 65536 2>/dev/null || true
VENV={spec.venv}
CODE_DIR={spec.code_dir}
CODE_URL={shlex.quote(spec.code_url)}
RUN_DIR={shlex.quote(spec.run_dir)}
STATUS_URL={shlex.quote(spec.status_url)}
LOG=/tmp/{spec.job_id}.log
STARTED_AT=$(date -uIs)
: > "$LOG"

# Mirror the log to GCS while the job runs, so a launcher (or a human) can
# watch a run it cannot ssh into.
( while sleep 20; do
    gcloud storage cp "$LOG" "$RUN_DIR/log.txt" >/dev/null 2>&1 || true
  done ) &
PUMP=$!
finish() {{
  kill "$PUMP" 2>/dev/null
  gcloud storage cp "$LOG" "$RUN_DIR/log.txt" >/dev/null 2>&1
  printf 'exit=%s\\n' "$1" | gcloud storage cp - "$STATUS_URL"
  # Read by the validator: distinguishes "finished" from "left a stale
  # final_result.json behind after crashing".
  printf '{{"state": "%s", "exit_code": %s, "seed": {spec.seed}, "job_id": "{spec.job_id}", "started_at": "'"$STARTED_AT"'", "finished_at": "'"$(date -uIs)"'"}}\\n' \\
    "$([ "$1" = 0 ] && echo COMPLETED || echo FAILED)" "$1" \\
    | gcloud storage cp - "$RUN_DIR/status.json"
  exit "$1"
}}

# `unattended-upgrades` owns the dpkg lock for the first minutes of a VM's
# life, so apt has to wait for it -- and every step here has to fail loudly,
# or the job limps on to a half-built venv.
apt_get() {{ apt-get -y -o DPkg::Lock::Timeout=900 "$@"; }}

install_python() {{
  for attempt in 1 2 3; do
    apt_get update &&
      apt_get install software-properties-common &&
      add-apt-repository -y ppa:deadsnakes/ppa &&
      apt_get update &&
      apt_get install python3.12 python3.12-venv python3.12-dev &&
      command -v python3.12 && return 0
    echo "apt attempt $attempt failed; retrying in 30s"
    sleep 30
  done
  return 1
}}

setup() {{
  # Serialised: several seeds may share a VM and must not race on apt/pip.
  (
    flock 9
{_apt_block(spec)}
    if [ ! -x "$VENV/bin/python" ]; then
      install_python || exit 1
      python3.12 -m venv "$VENV" || exit 1
      "$VENV/bin/pip" install -q -U pip wheel || exit 1
    fi
    if [ "$(cat $CODE_DIR/.launch_code_url 2>/dev/null)" != "$CODE_URL" ]; then
      rm -rf "$CODE_DIR"; mkdir -p "$CODE_DIR"
      gcloud storage cp "$CODE_URL" /tmp/simply_code.tar.gz || exit 1
      tar xzf /tmp/simply_code.tar.gz -C "$CODE_DIR" || exit 1
      (cd "$CODE_DIR" && "$VENV/bin/pip" install -q -U -e ".[{spec.pip_extras}]" \\
        google-crc32c \\
        -f https://storage.googleapis.com/jax-releases/libtpu_releases.html) || exit 1
{_protos_block(spec)}
      echo "$CODE_URL" > "$CODE_DIR/.launch_code_url"
    fi
  ) 9>/var/lock/simply-setup.lock
}}

{{
  set -x
  date -Is; hostname; uname -a
  setup
}} >> "$LOG" 2>&1
rc=$?
[ $rc -eq 0 ] || finish $rc

(
  # One job per VM holds the TPU. Nothing should ever queue two, but a
  # duplicate must fail fast rather than corrupt a run that is under way.
  flock -w 60 8 || {{ echo 'another job already holds this VM'; exit 75; }}
  set -x
  source "$VENV/bin/activate"
{indent(_assets_block(spec))}
{env_lines}
  export PYTHONPATH="$CODE_DIR:${{PYTHONPATH:-}}"
  cd "$CODE_DIR"
  python -c "import jax; print('jax', jax.__version__, jax.devices())"
  {command}
) 8>/var/lock/simply-tpu.lock >> "$LOG" 2>&1
finish $?
'''
