// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package server

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

// webdist holds the built SvelteKit SPA. The build output lives in
// webdist/client and is generated by `make frontend-build` (npm run build); it
// is git-ignored, so a checkout that hasn't built the frontend embeds only the
// README placeholder. The `all:` prefix is required to embed SvelteKit's
// `_app` directory (leading underscore).
//
//go:embed all:webdist
var webdistFS embed.FS

// clientFS returns the embedded SPA filesystem and whether a real build is
// present (i.e. index.html exists). When the frontend hasn't been built the
// directory is empty and built is false.
func clientFS() (fs.FS, bool) {
	sub, err := fs.Sub(webdistFS, "webdist/client")
	if err != nil {
		return nil, false
	}
	if _, err := fs.Stat(sub, "index.html"); err != nil {
		return sub, false
	}
	return sub, true
}

// staticHandler serves the embedded SPA: a real file when the path matches one,
// otherwise index.html so client-side routing works on deep links. If the
// frontend wasn't built, it returns a clear 503 instead of confusing 404s.
func (s *Server) staticHandler() http.Handler {
	sub, built := clientFS()
	if !built {
		return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "frontend not built; run: make frontend-build", http.StatusServiceUnavailable)
		})
	}
	files := http.FileServer(http.FS(sub))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		p := strings.TrimPrefix(r.URL.Path, "/")
		if p == "" {
			p = "index.html"
		}
		if f, err := sub.Open(p); err == nil {
			_ = f.Close()
			files.ServeHTTP(w, r)
			return
		}
		// Unknown path → SPA entry point.
		r.URL.Path = "/"
		files.ServeHTTP(w, r)
	})
}
